sudo: False
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8==3.3.0 pylint==1.8.1
  - python setup.py install
script:
  - flake8 --exclude __init__.py pyps4_homeassistant
  - pylint pyps4_homeassistant
  - python tests/test_media_art.py
  - python tests/test_ddp_protocol.py
branches:
  only:
  - master
  - dev
